name: build push
on:
  push:
    branches:
      - main
jobs:
  docker:
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: checkout
        uses: actions/checkout@v5
      - name: setup qemu
        uses: docker/setup-qemu-action@3
        with:
          platforms: arm64,amd64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: arm64,amd64
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:latest
          platforms: arm64,amd64
